---
title: "Flow Between Shelter System and Permanent Housing"
author: "Aliyah Maxine Ramos"
format: pdf
# editor: visual
# bibliography: references.bib
---

```{r}
#| echo: false
options(repos = list(CRAN="http://cran.rstudio.com/"))

# set-up packages
install.packages("opendatatoronto")
install.packages("tidyverse")
# read packages
library(opendatatoronto)
library(tidyverse)
library(dplyr)
library(ggplot2)
```

```{r}
#| echo: false

# download Toronto Shelter System Flow Data

library(opendatatoronto)
library(dplyr)

# get package
package <- show_package("ac77f532-f18b-427c-905c-4ae87ce69c93")
package

# get all resources for this package
resources <- list_package_resources("ac77f532-f18b-427c-905c-4ae87ce69c93")

# identify datastore resources; by default, Toronto Open Data sets datastore resource format to CSV for non-geospatial and GeoJSON for geospatial resources
datastore_resources <- filter(resources, tolower(format) %in% c('csv', 'geojson'))

# load the first datastore resource as a sample
data <- filter(datastore_resources, row_number()==1) %>% get_resource()
data
```

```{r}
#| echo: false
#| include: false
# graph of returned from housing data for families

```

